apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}
    version: {{ .Values.image.tag }}
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Values.image.tag }}
  name: {{ .Values.serviceName }}
  namespace: app
spec:
  ports:
    - port: 8080
      name: http-8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.serviceName }}

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.serviceName }}
  namespace: app
spec:
  host: {{ .Values.serviceName }}
  subsets:
    # Lihat di bagian labeling deployment spec, label deployment harus memiliki
    # version label untuk melakukan tagging
    - name: {{ .Values.image.tag }}
      labels:
        version: {{ .Values.image.tag }}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.serviceName }}
  namespace: app
spec:
  hosts:
    - frontend.local
  gateways:
    - {{ .Values.serviceName }}-gwy
  http:
    - route:
        - destination:
            host: {{ .Values.serviceName }}
            subset: {{ .Values.image.tag }}
            port: 
              number: 8080

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.serviceName }}-gwy
  namespace: app
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: "http-{{ .Values.serviceName }}"
      protocol: HTTP
    hosts:
      - frontend.local