apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}
    version: {{ .Values.image.tag }}
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Values.image.tag }}
  name: {{ .Values.serviceName }}
  namespace: app
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.serviceName }}
    version: {{ .Values.image.tag }}
