apiVersion: networking.istio.io/v1/alpha3
kind: VirtualService
metadata: 
  name: {{ .Values.serviceName }}
spec:
  hosts:
    - {{ .Values.serviceName }}
  http:
    - match:
    - route:
        - destination: {{ .Values.serviceName }}