apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}
    version: {{ .Values.image.tag }}
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Values.image.tag }}
  name: {{ .Values.serviceName }}
  namespace: app
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    # Tanpa perlu menyebutkan selector karena nanti akan di distribusikan oleh 
    # Destination rule
    app: {{ .Values.serviceName }}

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.serviceName }}
spec:
  host: {{ .Values.serviceName }}
  subsets:
    # Lihat di bagian labeling deployment spec, label deployment harus memiliki
    # version label untuk melakukan tagging
    - name: {{ .Values.image.tag }}
      labels:
        version: {{ .Values.image.tag }}
    - name: v1
      labels:
        version: v1

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.serviceName }}
spec:
  hosts:
    - {{ .Values.serviceName }}
  http:
    - route:
        - destination:
            host: {{ .Values.serviceName }}
            subset: {{ .Values.image.tag }}
